import { test, expect } from './myTestData';
import * as userData from '../testData/UserInfo.json';
import { executeQuery } from '../testData/database.utils';
import LoginPage from '../testData/LoginPage';
import * as fs from 'fs';
import * as path from 'path';

// Removed unused Page type and browser.newPage setup
//Jira created filter by TAXID not working. To be automated once the issue is resolved.

test('AccountDashboard control/elements verification test execution', async ({ page, loginAsAdmin }) => {
  await loginAsAdmin();

  await expect(page.getByRole('link', { name: ' Accounts' })).toBeVisible();
  await expect(page.getByRole('link', { name: ' Accounts' })).toContainText('Accounts');
  await page.getByRole('link', { name: ' Accounts' }).click();
  await expect(page.locator('app-accounts').getByText('Accounts', { exact: true })).toHaveText('Accounts');
  await page.locator('app-accounts').getByText('Accounts', { exact: true }).click();
  await page.getByRole('link', { name: ' Accounts' }).click();

  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('columnheader', { name: 'account number ' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Name', exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'State' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'City' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Address' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'contact Name' })).toBeVisible();
  await expect(page.getByRole('link').filter({ hasText: /^$/ }).nth(1)).toBeVisible();
  await expect(page.getByRole('cell', { name: '000VMTEST' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'WISOKY, MANTE AND ORTIZ' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'LA' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'SOUTH ISADORE' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'MR. JEWEL KEELING I' })).toBeVisible();
  await expect(page.getByRole('cell').filter({ hasText: 'Edit AccountDeactivate' }).first()).toBeVisible();
  await expect(page.getByText('Account Number', { exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Account Number' }).click();
  await expect(page.getByRole('textbox', { name: 'Enter Account Number' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Account Number' }).fill('000VMTEST');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('cell', { name: '000VMTEST' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Name', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'WISOKY, MANTE AND ORTIZ' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Account Number' }).click();
  await page.getByRole('textbox', { name: 'Enter Account Number' }).fill('');
  await expect(page.getByText('Account Name')).toBeVisible();  
  await page.getByRole('textbox', { name: 'Enter Account Name' }).click();
  await expect(page.getByRole('textbox', { name: 'Enter Account Name' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Account Name' }).fill('Mante');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('columnheader', { name: 'Name', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'WISOKY, MANTE AND ORTIZ' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Account Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Account Name' }).fill('');
  await expect(page.locator('form').getByText('City')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Enter City' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter City' }).fill('SOUTH');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('columnheader', { name: 'City' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'SOUTH ISADORE' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter City' }).click();
  await page.getByRole('textbox', { name: 'Enter City' }).fill('');
  await expect(page.locator('span').filter({ hasText: 'State' })).toBeVisible();
  await page.locator('states').getByRole('combobox').selectOption('LA');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('columnheader', { name: 'State' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'LA' }).first()).toBeVisible();
  await page.locator('states').getByRole('combobox').selectOption('');
  await expect(page.getByText('Vendor', { exact: true })).toBeVisible();
  await expect(page.locator('dropdown-filter-item')).toContainText('Select Vendor');
  await page.locator('dropdown-filter-item').getByRole('combobox').selectOption('15: H');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('cell', { name: 'CARE0052P10313G19415' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'DANIEL-KERLUKE' })).toBeVisible();
  await page.locator('dropdown-filter-item').getByRole('combobox').selectOption('');
  await expect(page.getByText('NPI')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter NPI' }).click();
  await page.getByRole('textbox', { name: 'Enter NPI' }).fill('0829876198');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('columnheader', { name: 'account number ' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'VMCTEST' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Name', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'HAGENES-WEISSNAT' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter NPI' }).click();
  await page.getByRole('textbox', { name: 'Enter NPI' }).fill('');
});


test('Account Sorting search results control/elements verification test execution', async ({ page }) => {
  let loginPage = new LoginPage(page);
  await loginPage.navigate();
  await loginPage.login(userData.admin.username, userData.admin.password);
  await expect(page).toHaveURL(userData.admin.dashboardUrl);

  await expect(page.getByRole('link', { name: ' Accounts' })).toBeVisible();
  await expect(page.getByRole('link', { name: ' Accounts' })).toContainText('Accounts');
  await page.getByRole('link', { name: ' Accounts' }).click();
  await expect(page.locator('app-accounts').getByText('Accounts', { exact: true })).toHaveText('Accounts');
  await page.locator('app-accounts').getByText('Accounts', { exact: true }).click();
  await page.getByRole('link', { name: ' Accounts' }).click();

  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByText('Account NumberAccount')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Provider Group ID' }).click();
  await page.getByRole('textbox', { name: 'Enter Provider Group ID' }).fill('G00014');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(1).click();
  await expect(page.getByRole('cell', { name: 'G00014', exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Group ID' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Provider Group ID' }).click();
  await page.getByRole('textbox', { name: 'Enter Provider Group ID' }).fill('');
  await expect(page.getByText('Provider ID', { exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Provider ID' }).click();
  await page.getByRole('textbox', { name: 'Enter Provider ID' }).fill('T00063');
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(3).click();
  await expect(page.getByRole('columnheader', { name: 'provider ID' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'T00063', exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter Provider ID' }).click();
  await page.getByRole('textbox', { name: 'Enter Provider ID' }).fill('');
  await expect(page.getByText('Show Inactive Only')).toBeVisible();
  await page.getByRole('checkbox', { name: 'Show Inactive Only' }).check();
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await expect(page.getByRole('cell', { name: 'E2ETESTACCOUNT01', exact: true })).toBeVisible();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(4).click();
  await expect(page.getByRole('link').filter({ hasText: /^$/ }).nth(4)).toBeVisible();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('checkbox', { name: 'Show Inactive Only' }).uncheck();
  await page.getByRole('button', { name: 'Apply Filter' }).click();
  await page.getByRole('columnheader', { name: 'account number ' }).click();
  await page.getByRole('columnheader', { name: 'account number ' }).click();
  await expect(page.getByRole('columnheader', { name: 'account number ' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '000VMTEST' })).toBeVisible();
  await page.getByRole('columnheader', { name: 'Name', exact: true }).click();
  await expect(page.getByRole('columnheader', { name: 'Name ' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'ABBOTT-GERLACH' })).toBeVisible();
  await page.getByRole('columnheader', { name: 'State' }).click();
  await expect(page.getByRole('columnheader', { name: 'State ' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'AB', exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'City' })).toBeVisible();
  await page.getByRole('columnheader', { name: 'City' }).click();
  await expect(page.getByRole('cell', { name: 'AARONSBURG' }).first()).toBeVisible();
  await page.getByRole('columnheader', { name: 'Address' }).click();
  await expect(page.getByRole('columnheader', { name: 'Address ' })).toBeVisible();
  await page.getByRole('columnheader', { name: 'Address ' }).click();
  await page.getByRole('columnheader', { name: 'Address ' }).click();
  await expect(page.getByRole('cell', { name: 'SILVER FANG STREET' })).toBeVisible();
  await page.getByRole('columnheader', { name: 'contact Name' }).click();
  await page.getByRole('columnheader', { name: 'contact Name ' }).click();
  await expect(page.getByRole('columnheader', { name: 'contact Name ' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Not provided' }).first()).toBeVisible();
  await page.getByRole('columnheader', { name: 'account number' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(2).click();
  await expect(page.getByRole('link').filter({ hasText: /^$/ }).nth(2)).toBeVisible();
});