 import { test, expect, Page } from '@playwright/test';
import * as userData from '../testData/UserInfo.json';
import { getTodaysDate, getTodaysDateWithYr } from '../testData/database.utils';
import LoginPage from '../testData/LoginPage';

import {  isActiveAccount } from '../testData/database.utils';
// Helper: ensure a textbox (by accessible name) has a value; fill if empty
async function ensureInputHasValue(page: Page, roleName: string, value: string) {
  const textbox = page.getByRole('textbox', { name: roleName });
  const current = await textbox.inputValue();
  if (!current) {
    await textbox.fill(value);
  }
}


let page: Page;
test.beforeEach(async ({ browser }) => {
  // Initialize the page instance before each test
  page = await browser.newPage();
  });


test('Create Provider Group Screen verification and functionality test', async ({ page }) => {
  let loginPage = new LoginPage(page);
  await loginPage.navigate();
  await loginPage.login(userData.admin.username, userData.admin.password);
  await expect(page).toHaveURL(userData.admin.dashboardUrl);
  
  
await page.getByRole('link', { name: ' Accounts' }).click();
await page.getByRole('textbox', { name: 'Enter Account Number' }).click();
await page.getByRole('textbox', { name: 'Enter Account Number' }).fill(userData.providerGroup.accountNum);
await page.getByRole('button', { name: 'Apply Filter' }).click();
await expect(page.getByRole('link').filter({ hasText: /^$/ }).nth(2)).toBeVisible();
await page.getByRole('link').filter({ hasText: /^$/ }).nth(2).click();
await expect(page.getByRole('button', { name: 'Add Provider Group' })).toBeVisible();
await page.getByRole('button', { name: 'Add Provider Group' }).click();
await expect(page.getByRole('heading', { name: 'Create Provider Group' })).toBeVisible();
await expect(page.getByRole('tab', { name: 'Provider Details' })).toBeVisible();
await expect(page.getByRole('tab', { name: 'Identifiers' })).toBeVisible();
await expect(page.getByRole('tab', { name: 'Processor' })).toBeVisible();
await expect(page.getByRole('tab', { name: 'Financial Settings' })).toBeVisible();
await expect(page.getByText('* account number')).toBeVisible();
await expect(page.getByLabel('Provider Details').locator('form')).toContainText('* account number');
await expect(page.locator('.col-3 > div').first()).toBeVisible();
await expect(page.getByText('* name')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Group Name' })).toHaveValue(userData.providerGroup.accountNum);
await expect(page.getByRole('textbox', { name: 'Enter Group Name' })).toBeVisible();
await expect(page.getByText('* fee schedule')).toBeVisible();
await expect(page.getByLabel('feeSchedule')).not.toBeEmpty();
await expect(page.getByLabel('feeSchedule')).toBeVisible();
await expect(page.getByLabel('feeSchedule')).toContainText('Select Fee Schedule CLAIMSCOMPLETE FLAT 45 NIC ONLY CORPORATE PROVIDER RATE (RIDGEMARK/NORTHE NIC_ONLY NO FEE SCHEDULE SET NOT APPLICABLE TH-CLAIMSCOMPLETE2 TH DUPLICATE PROVIDER (FOR ADMIN - NO SERVICE FEE) TH FLAT FEE TH SPECIAL GROUP (NOT USED) TH UNLIMITED PER PROVIDER TH VOLUME DISCOUNT THERAPIST HELPER 1 PROVIDER V10');
await page.getByLabel('feeSchedule').selectOption('F0256');
await expect(page.getByText('* Practice Management')).toBeVisible();
await expect(page.locator('ddl-practice')).toContainText('Select Practice Management 1 HSS CONTROL COMPANY (H06) 1DOCTORS RESOURCE SPECIALISTS CP (H05) ACE BILLING SERVICES (A1) ACPM (A) ADVANCED (XX1) ADVANCED BILLING LLC CP (H19) AEGIS BUSINESS SERVICES LLC (H01) AFFORDABLE MEDICAL BILLING CP (H08) ALN MEDICAL MANAGEMENT CP (H13) AMAZING CHARTS CP (G03) APG CP (H12) ARGUS MEDICAL CP (H14) BENCHMARK (BMK) BIZMATICS (Z) CARETRACKER (H) CARETRACKER_TEST (TST) CFDS (C) CLINIX MEDICAL INFORMATION SERVICES (CLX) COMTECH CONSULTING GROUP INC CP (H15) CT-RESELLER2 (G) DABBS COMPUTER CONSULTANTS LLC CP (H02) DOCS BILLING SOLUTIONS CP (H17) DOCTOR (I) EASTERN POINT RCM LLC CP (H29) EVOLVE (E) FACULTY PRACTICE SERVICES INC CP (H21) FLATIRONS PRACTICE MANAGEMENT CP (H16) FLORIDA MEDICAL CP (H22) FOCUS MEDICAL SOLUTIONS LLC CP (H61) GOOD SHEPHERD MEDICAL CP (G01) GURU MEDICAL CP (H24) HARRIS RCM PORTAL (G04) HEALTHCARE MANAGEMENT SERVICES CP (H26) HEALTHCARE SUPPORT TECHNOLOGIES CP (H27) JCNR BILLING LLC CP (G02) LAKEFRONT BILLING SERVICE INC CP (H30) LEGACY (L) LPC CONTROL COMPANY CP (H04) MCKESSON CP (H31) MEDENET INC CP (H32) MEDFX (QFX) MEDI SERV INC CP (H33) MEDICAL BILLING PRACTICE MANAGEMENT INC CP (H34) MEDICAL BILLING SOLUTIONS INC CP (H35) MEDICAL BILLING SPECIALISTS CP (H36) MEDICAL DATA CONSULTANTS INC. CP (H57) MEDICAL HELPER (M) MEDICAL OFFICE SYS (F) MEDORIZON CP (H62) MEDORIZON OF TX CP (H40) MEDRIUM (X) MERGE HEALTHCARE CP (H43) MGSI LLC CP (H41) NATH HEALTHCARE BUSINESS SOLUTIONS LLC CP (H42) NHA (N) NOD-US BILLING (U) OBGYN (O) OPTUM 360 (H60) PATIENT ACCOUNT SERVICES CP (H46) PREMIER BILLING NETWORK CP (H48) PROSERVE PRACTICE MANAGEMENT CP (H49) PRS LLC (PHASIS) CP (H6A) PULSE (D) PULSECLOUD (B) QUANTIX CP (H55) RESPONSE (V) REVENUE MANAGEMENT SOLUTIONS LLC CP (H50) REVPRO HEALTHCARE SOLUTIONS CP (H44) RIDGEMARK (R) SECURECONNECT (SC) SECURECONNECT (SC1) SRS CP (H7A) STRIVANT HEALTH LLC CP (H07) SYNAPSE PRACTICE MANAGEMENT CP (H54) SYSINFORMATION CP (H53) TEAMPRAXIS (PRX) TEST_ACCOUNT (T) THERAPIST HELPER (P) THIS IS TO TEST (AGP) ULTIMATE BILLING (H52) UNISLINK CP (H18) WEHRMAN HEALTHCARE MANAGEMENT SOLUTIONS LLC CP (H51)');
await expect(page.locator('ddl-practice').getByRole('combobox')).toBeVisible();
await expect(page.locator('ddl-practice').getByRole('combobox')).toHaveValue('H');
await expect(page.getByText('* certification status')).toBeVisible();
await expect(page.getByLabel('Provider Details').locator('form')).toContainText('Production');
await expect(page.getByLabel('Provider Details').locator('form')).toContainText('Test');
await page.getByText('Test', { exact: true }).click();
await expect(page.getByText('Contact', { exact: true })).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Contact' })).toHaveValue('KATHIJA');
await expect(page.getByRole('textbox', { name: 'Enter Contact' })).toBeVisible();
await expect(page.getByText('Title')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Title' })).toBeEmpty();
await expect(page.getByText('Phone')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Phone' })).toHaveValue('(446) 774-4222');
await expect(page.getByRole('textbox', { name: 'Enter Phone' })).toBeVisible();
await expect(page.getByText('Fax')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Fax' })).toBeVisible();
await expect(page.locator('section-contact').getByText('email')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Email' })).toHaveValue('kmohamed@harriscomputer.com');
await expect(page.getByRole('textbox', { name: 'Enter Email' })).toBeVisible();
await expect(page.getByText('Address 1')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Address' }).first()).toHaveValue('112 SILVER FANG DR');
await expect(page.getByRole('textbox', { name: 'Enter Address' }).first()).toBeVisible();
await expect(page.getByText('address 2')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Address' }).nth(1)).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Address' }).nth(1)).toBeEmpty();
await expect(page.getByText('Zip', { exact: true })).toBeVisible();

await expect(page.locator('ng-select').filter({ hasText: 'Enter ZIP 70510 ×' }).getByRole('combobox')).toBeVisible();
await expect(page.locator('ng-select').filter({ hasText: 'Enter City ABBEVILLE ×' }).getByRole('combobox')).toBeVisible();
await expect(page.locator('ng-select').filter({ hasText: 'Enter State×LA×' }).getByRole('combobox')).toBeVisible();
await expect(page.getByLabel('Provider Details').getByText('City', { exact: true })).toBeVisible();
await expect(page.locator('div:nth-child(2) > .ng-select-searchable > .ng-select-container > .ng-value-container > .ng-input > input')).toBeVisible();
await expect(page.getByText('state', { exact: true })).toBeVisible();
await expect(page.locator('div:nth-child(3) > .ng-select-searchable > .ng-select-container > .ng-value-container > .ng-input > input')).toBeVisible();
await expect(page.locator('checkbox').filter({ hasText: 'ECS' })).toBeVisible();
await expect(page.locator('section-status-dates')).toContainText('ECS');
await expect(page.getByRole('checkbox', { name: 'ERA', exact: true })).toBeVisible();
await expect(page.getByLabel('Provider Details').getByText('ERA', { exact: true })).toBeVisible();
await expect(page.getByText('/11/26').first()).toBeVisible();
await expect(page.getByText('/11/26').nth(1)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Claim Status' })).toBeVisible();
await expect(page.getByText('Claim Status')).toBeVisible();
await expect(page.getByText('/11/26').nth(2)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Eligibility' })).toBeVisible();
await expect(page.locator('checkbox').filter({ hasText: 'Eligibility' })).toBeVisible();
await expect(page.getByText('/11/26').nth(3)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Statements', exact: true })).toBeVisible();
await expect(page.getByText('Statements', { exact: true })).toBeVisible();
await expect(page.getByText('/11/26').nth(4)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Claims Correct' })).toBeVisible();
await expect(page.getByText('Claims Correct')).toBeVisible();
await expect(page.getByText('N/A')).toBeVisible();
await expect(page.getByText('/11/26').nth(4)).toBeVisible();
await expect(page.getByText('RCM', { exact: true })).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'RCM' })).toBeVisible();
await expect(page.getByText('Generic Provider')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Generic Provider' })).toBeVisible();
await expect(page.getByText('lockbox', { exact: true })).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter LockBox' })).toBeVisible();
await expect(page.getByText('backlink')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Backlink' })).toBeVisible();
await expect(page.getByText('Lockbox Processor id')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Processor Id' })).toBeVisible();
await expect(page.getByText('Notes')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Notes' })).toBeVisible();
await expect(page.getByText('Add Group Enrollment Batch')).toBeVisible();
await expect(page.getByLabel('Provider Details').locator('form')).toContainText('Add Group Enrollment Batch reports 277ca 277u Pulse CSV Human Readable Machine Readable XML Generate 999 remittance 277ca 277u CSV ERA Summary Human Readable Machine Readable XML Daily Pulse CSV Human Readable 271 Reject Print Claims Alphall New Statements Combine ERA Glue era Combine ALL NoBy Payer');
await expect(page.getByText('Batch reports')).toBeVisible();
await expect(page.getByText('277ca').first()).toBeVisible();
await expect(page.getByRole('checkbox', { name: '277ca' }).first()).toBeVisible();
await expect(page.locator('label').filter({ hasText: '277u' }).first()).toBeVisible();
await expect(page.getByText('277u').first()).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Pulse CSV', exact: true })).toBeVisible();
await expect(page.getByText('Pulse CSV', { exact: true })).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Human Readable' }).first()).toBeVisible();
await expect(page.getByText('Human Readable').first()).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Machine Readable' }).first()).toBeVisible();
await expect(page.getByText('Machine Readable').first()).toBeVisible();
await expect(page.locator('label').filter({ hasText: 'XML' }).first()).toBeVisible();
await expect(page.getByText('XML').first()).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Generate' })).toBeVisible();
await expect(page.getByText('Generate')).toBeVisible();
await expect(page.getByText('remittance')).toBeVisible();
await expect(page.getByRole('checkbox', { name: '277ca' }).nth(1)).toBeVisible();
await expect(page.getByText('277ca').nth(1)).toBeVisible();
await expect(page.getByRole('checkbox', { name: '277u' }).nth(1)).toBeVisible();
await expect(page.getByText('277u').nth(1)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'CSV', exact: true })).toBeVisible();
await expect(page.getByText('CSV', { exact: true })).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'ERA Summary' })).toBeVisible();
await expect(page.getByText('ERA Summary')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Human Readable' }).nth(1)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Machine Readable' }).nth(1)).toBeVisible();
await expect(page.getByText('Machine Readable').nth(1)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'XML' }).nth(1)).toBeVisible();
await expect(page.getByText('XML').nth(1)).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Daily Pulse CSV' })).toBeVisible();
await expect(page.getByText('Daily Pulse CSV')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Human Readable 271' })).toBeVisible();
await expect(page.getByText('Human Readable 271')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Reject Print Claims' })).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Reject Print Claims' })).toBeChecked();
await expect(page.getByText('Reject Print Claims')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Alphall' })).toBeVisible();
await expect(page.locator('section-batch-remittance')).toContainText('Alphall');
await expect(page.getByText('Alphall')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'New Statements' })).toBeVisible();
await expect(page.getByText('New Statements')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Combine ERA' })).toBeVisible();
await expect(page.getByText('Combine ERA')).toBeVisible();
await expect(page.getByText('Glue era')).toBeVisible();
await expect(page.getByText('Combine ALL')).toBeVisible();
await expect(page.getByText('No', { exact: true })).toBeVisible();
await expect(page.getByText('By Payer')).toBeVisible();
await page.getByText('Combine ALL').click();
await page.getByRole('checkbox', { name: 'Combine ERA' }).check();
await page.getByRole('checkbox', { name: 'Machine Readable' }).first().check();
await page.getByRole('tab', { name: 'Identifiers' }).click();
await page.getByRole('tab', { name: 'Identifiers' }).click();
await expect(page.getByRole('tab', { name: 'Identifiers' })).toBeVisible();
await expect(page.getByText('Identifier', { exact: true })).toBeVisible();
await expect(page.getByRole('combobox')).toContainText('Select Identifier 0B - State License 1A - Blue Cross 1B - Blue Shield 1C - Medicare 1D - Medicaid 1G - UPIN 1H - Champus 1J - Facility B3 - PPO BQ - HMO EI - EIN FH - Clinic G2 - Commercial G5 - Site LU - Location N5 - Plan Network Id RR - Medicare Rail Road U3 - USIN X5 - State Ind Accident XX - NPI PR - ERA Prefix TX - Taxonomy Code');
await expect(page.getByLabel('Identifiers').getByText('ID', { exact: true })).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Id' })).toBeVisible();
await expect(page.getByRole('columnheader', { name: 'name' })).toBeVisible();
await expect(page.getByRole('columnheader', { name: 'Id' })).toBeVisible();
await expect(page.locator('.ng-untouched > .row > div:nth-child(3)').first()).toBeVisible();
await page.getByRole('combobox').selectOption('11: Object');
await page.getByRole('textbox', { name: 'Enter Id' }).click();
await page.getByRole('textbox', { name: 'Enter Id' }).fill('680522753');
await expect(page.getByRole('button', { name: 'Add Details' })).toBeVisible();
await page.getByRole('button', { name: 'Add Details' }).click();
await page.getByRole('combobox').selectOption('20: Object');
await page.getByRole('textbox', { name: 'Enter Id' }).click();
await page.getByRole('textbox', { name: 'Enter Id' }).fill('1083743850');
await page.getByRole('button', { name: 'Add Details' }).click();
await page.getByRole('tab', { name: 'Financial Settings' }).click();
await expect(page.getByText('Account Credential Key')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Account Credential Key' })).toBeVisible();
await expect(page.getByText('Allow ACH')).toBeVisible();
await expect(page.getByRole('tabpanel', { name: 'Financial Settings' }).locator('radio')).toBeVisible();
//await expect(page.locator('.ng-untouched.ng-pristine > .input-wrap > .text')).toBeVisible();
//await page.locator('.ng-untouched.ng-pristine > .input-wrap > .text').click();

await page.getByRole('tabpanel', { name: 'Financial Settings' }).locator('radio').click();
//await page.locator('.col-4 > .ng-select-searchable > .ng-select-container > .ng-clear-wrapper').click();

await page.getByRole('textbox', { name: 'Enter Account Credential Key' }).click();
await ensureInputHasValue(page, 'Enter Account Credential Key', '144789693367:66979f6aa2eb4094bba2f74cc8ac2821');
const value = await page.getByRole('textbox', { name: 'Enter Account Credential Key' }).inputValue();
if (value === '144789693367:66979f6aa2eb4094bba2f74cc8ac2821') {
  await page.getByRole('combobox').click();
  await expect(page.getByRole('combobox').getByRole('textbox')).toBeVisible();
  await expect(page.getByRole('combobox').getByRole('textbox')).toBeEnabled();
  await page.getByText('CareTracker', { exact: true }).click();
}
await expect(page.getByText('ACH Credential Key')).toBeVisible();
await expect(page.getByText('Account Credential Key Allow')).toBeVisible();
await page.getByText('Account Credential Key Allow').click();
await expect(page.getByText('Payments Partner', { exact: true })).toBeVisible();
await expect(page.getByText('Transaction Devices')).toBeVisible();
await expect(page.getByRole('columnheader', { name: 'Device Name ▼' })).toBeVisible();
await expect(page.getByRole('columnheader', { name: 'Device Identifier ▼' })).toBeVisible();
await expect(page.getByRole('columnheader', { name: 'Credential Key ▼' })).toBeVisible();
await expect(page.getByRole('button', { name: 'Add Device' })).toBeVisible();
await page.getByRole('button', { name: 'Add Device' }).click();
await expect(page.getByRole('heading', { name: 'Add New Transaction Device' })).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Is Default' })).toBeVisible();
await expect(page.getByText('Is Default')).toBeVisible();
await expect(page.getByText('Is DefaultDevice NameDevice')).toBeVisible();
await expect(page.getByRole('textbox').nth(3)).toBeVisible();
await expect(page.getByText('Device Identifier', { exact: true })).toBeVisible();
await expect(page.getByRole('textbox').nth(4)).toBeVisible();
await expect(page.getByText('Credential Key (optional)')).toBeVisible();
await expect(page.getByText('Credential Key (optional)')).toBeVisible();
await expect(page.getByRole('textbox').nth(5)).toBeVisible();
await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
await expect(page.getByRole('button', { name: 'Save' })).toBeVisible();
await page.getByRole('textbox').nth(3).click();
await page.getByRole('textbox').nth(3).fill('Kathija\'s Device');
await page.getByRole('textbox').nth(4).click();
await page.getByRole('textbox').nth(4).click();
await page.getByRole('textbox').nth(4).fill('a4hos7');
await page.getByRole('textbox').nth(5).click();
await page.getByRole('textbox').nth(5).fill('144789693367:66979f6aa2eb4094bba2f74cc8ac2821');
await page.getByRole('checkbox', { name: 'Is Default' }).check();
await page.getByRole('button', { name: 'Save' }).click();
await expect(page.getByRole('button', { name: 'Manage Configuration' })).toBeVisible();
await page.getByRole('button', { name: 'Manage Configuration' }).click();
await page.getByRole('button', { name: 'Manage Configuration' }).click();
await expect(page.getByRole('button', { name: 'Add & Close' })).toBeVisible();
await page.getByRole('button', { name: 'Add & Close' }).click();
await expect(page.getByRole('heading', { name: 'Confirm action' })).toBeVisible();
await expect(page.getByText('Do you want to add provider')).toBeVisible();
await expect(page.getByRole('button', { name: 'No' })).toBeVisible();
await expect(page.getByRole('button', { name: 'Yes' })).toBeVisible();
await page.getByRole('button', { name: 'Yes' }).click();
await page.getByRole('textbox', { name: 'Enter First Name' }).click();
await expect(page.getByRole('heading', { name: 'Add Provider Setup 1/' })).toBeVisible();
await expect(page.getByText('* First name')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter First Name' })).toBeVisible();
await expect(page.getByText('* last name')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Last Name' })).toBeVisible();
await expect(page.getByRole('dialog').getByText('* Practice Management')).toBeVisible();
await expect(page.getByRole('dialog').getByText('* Practice Management Select')).toBeVisible();
await expect(page.getByRole('dialog').getByText('Address 1')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Enter Address' }).first()).toBeVisible();
await expect(page.getByRole('dialog').getByText('Zip', { exact: true })).toBeVisible();

await expect(page.locator('ng-select').filter({ hasText: 'Enter ZIP 70510 ×' }).getByRole('combobox')).toBeVisible();
await expect(page.locator('ng-select').filter({ hasText: 'Enter City ABBEVILLE ×' }).getByRole('combobox')).toBeVisible();
await expect(page.locator('ng-select').filter({ hasText: 'Enter State×LA×' }).getByRole('combobox')).toBeVisible();

//await expect(page.locator('.d-flex.flex-column.ng-touched > .address-wrapper > div > .ng-select-searchable > .ng-select-container > .ng-value-container > .ng-input > input').first()).toBeVisible();
await expect(page.getByRole('dialog').getByText('City', { exact: true })).toBeVisible();
//await expect(page.locator('.d-flex.flex-column.ng-touched > .address-wrapper > div:nth-child(2) > .ng-select-searchable > .ng-select-container > .ng-value-container > .ng-input > input')).toBeVisible();
await expect(page.getByRole('dialog').getByText('state', { exact: true })).toBeVisible();
//await expect(page.locator('.d-flex.flex-column.ng-touched > .address-wrapper > div:nth-child(3) > .ng-select-searchable > .ng-select-container > .ng-value-container > .ng-input > input')).toBeVisible();
await expect(page.getByRole('dialog').locator('checkbox').filter({ hasText: 'ECS' })).toBeVisible();
await expect(page.getByText('N/A').nth(3)).toBeVisible();
await expect(page.locator('.d-flex.mt-2 > .ng-touched > .checkbox').first()).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Claim Status' })).toBeVisible();
await expect(page.getByRole('dialog').getByText('Claim Status')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Eligibility' })).toBeVisible();
await expect(page.getByRole('dialog').getByText('Claim Status')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Eligibility' })).toBeVisible();
await expect(page.getByRole('dialog').getByText('Eligibility')).toBeVisible();
await expect(page.getByRole('checkbox', { name: 'Statements' })).toBeVisible();
await expect(page.getByRole('dialog').getByText('Statements')).toBeVisible();
await expect(page.getByText('N/A').nth(3)).toBeVisible();
await expect(page.getByText('N/A').nth(4)).toBeVisible();
await expect(page.getByText('N/A').nth(5)).toBeVisible();
await expect(page.locator('.ng-touched > .mb-3 > div:nth-child(4) > .input-text')).toBeVisible();
await expect(page.locator('.ng-touched > .mb-3 > div:nth-child(5) > .input-text')).toBeVisible();
await expect(page.getByRole('dialog').getByText('* fee schedule')).toBeVisible();
await expect(page.getByRole('combobox').nth(1)).toBeVisible();
await expect(page.getByRole('button', { name: 'Next' })).toBeVisible();
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Previous' }).click();
await page.getByRole('textbox', { name: 'Enter First Name' }).click();
await page.getByRole('textbox', { name: 'Enter First Name' }).fill('Provider001');
await page.getByRole('textbox', { name: 'Enter Last Name' }).click();
await page.getByRole('textbox', { name: 'Enter Last Name' }).fill('test');
await page.getByRole('button', { name: 'Next' }).click();
await expect(page.getByRole('button', { name: 'Save' })).toBeVisible();
await page.getByRole('button', { name: 'Save' }).click();
await page.getByText('Edit provider group Provider').click();
await page.getByText('Accounts Add Account').click();
});