import { test, expect } from './myTestData';
import { Locator, Page } from '@playwright/test';
import * as userData from '../testData/UserInfo.json';
import LoginPage from '../testData/LoginPage';
import helperFunction from '../testData/helperFunction';
import { existsBulkGroupEnrollment,  fetchNPIAndTaxIDForGroupId, fetchProviderGroupById, getTodaysDateWithFullYear, getTodaysDateWithYr } from '../testData/database.utils';
// Adding Bulk Group enrollment for groupid G00016
let page: Page;

// Setup: runs before each test
test.beforeEach(async ({ browser }) => {
  // [REVIEW] The following page initialization is commented out as it may be redundant or cause issues with Playwright's test runner.
  // page = await browser.newPage();
  // Please review if this is needed.
});
test('Add Bulk Group Enrollment ', async ({ page, loginAsAdmin }) => {

  // --- Login ---
  await loginAsAdmin();
  const groupId = userData.groupEnroll.bulkgroupId;
  // --- Pre-checks and navigation ---
  const verifyEnrollmentExists = await existsBulkGroupEnrollment(groupId);
  await page.getByRole('link', { name: ' Group Enrollments' }).click();
  await page.getByRole('link', { name: ' Add Group Enrollment' }).click();

  const group = await fetchProviderGroupById(groupId);
  console.log(group); // { id: 'G00017', name: '...' } or null
  const groupName = group?.name;
  if (!groupName) throw new Error(`No group name found for groupId: ${groupId}`);

  const billingMap = await fetchNPIAndTaxIDForGroupId(groupId);
  const NPI = billingMap?.has('1699873976') ? '1699873976' : '';
  const TAXID = billingMap?.has('271673289') ? '271673289' : '';
  if (!NPI) throw new Error(`NPI value 1699873976 not found for groupId ${groupId}`);
  if (!TAXID) throw new Error(`TAXID value 271673289 not found for groupId ${groupId}`);

  await expect(page.getByRole('heading', { name: 'Add Group Enrollments' })).toBeVisible();
  await expect(page.getByRole('dialog').getByText('Group ID', { exact: true })).toBeVisible();
  await expect(page.getByRole('combobox').filter({ hasText: /^$/ })).toBeVisible();
  await expect(page.getByRole('textbox')).toBeEmpty();
  await expect(page.getByRole('dialog').getByText('NPI', { exact: true })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Select NPI$/ })).toBeVisible();
  await expect(page.getByText('tax id', { exact: true })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Select Tax Id$/ })).toBeVisible();
  await page.getByRole('textbox').click();
  await page.getByText(userData.groupEnroll.bulkgroupId).click();
  await expect(page.getByRole('textbox')).toBeVisible();
  await page.getByRole('combobox').nth(1).selectOption(NPI);
  await page.getByRole('combobox').nth(2).selectOption(TAXID);
  await expect(page.getByRole('heading', { name: 'Add Group Enrollments' })).toBeVisible();
  await expect(page.getByText('Group Name')).toBeVisible();
 // await expect(page.getByRole('dialog').getByText('Group ID')).toBeVisible();
  await expect(page.getByText(groupName)).toBeVisible();
  await expect(page.getByText(userData.groupEnroll.bulkgroupId)).toBeVisible();
 // await expect(page.getByRole('dialog').getByText('NPI')).toBeVisible();
  await expect(page.getByText(NPI)).toBeVisible();
  await expect(page.getByText('tax id', { exact: true })).toBeVisible();
  await expect(page.getByText(TAXID)).toBeVisible();
  // Debug log and screenshot before assertion
  const payerHeader = page.locator('#data-grid-header').getByText('Payer');
  const headerCount = await payerHeader.count();
  console.log('Payer header count:', headerCount);
  await page.screenshot({ path: 'payer-header-before-assertion.png', fullPage: true });
  await expect(payerHeader).toBeVisible();
  await expect(page.getByText('Enrollment Type', { exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Professional' }).getByRole('button')).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Professional' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Institutional' }).getByRole('button')).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Institutional' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'ERA' }).getByRole('button')).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'ERA' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Claim Status' }).getByRole('button')).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Claim Status' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Eligibility' }).getByRole('button')).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Eligibility' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'SELECTCARE' })).toBeVisible();
  await expect(page.getByRole('cell').nth(1)).toBeVisible();
  await expect(page.getByRole('cell').nth(2)).toBeVisible();
  await expect(page.getByRole('cell').nth(3)).toBeVisible();
  await expect(page.getByRole('cell').nth(4)).toBeVisible();
  await expect(page.getByRole('cell').nth(5)).toBeVisible();
  await expect(page.getByRole('cell').filter({ hasText: /^$/ }).nth(5)).toBeVisible();
  await expect(page.getByRole('cell', { name: 'S & S HEALTHCARE STRATEGIES' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'N/A' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'N/A' }).nth(1)).toBeVisible();
  await expect(page.locator('tr:nth-child(2) > td:nth-child(4)')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'N/A' }).nth(2)).toBeVisible();
  await expect(page.getByRole('cell', { name: 'N/A' }).nth(3)).toBeVisible();
  await expect(page.getByRole('row', { name: 'S & S HEALTHCARE STRATEGIES N' }).getByRole('link')).toBeVisible();
  await expect(page.locator('tr:nth-child(2) > td:nth-child(7)')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'PREFERRED COMMUNITY CHOICE /' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'N/A' }).nth(4)).toBeVisible();
  await expect(page.getByRole('cell', { name: 'N/A' }).nth(5)).toBeVisible();
  await expect(page.locator('tr:nth-child(3) > td:nth-child(4)')).toBeVisible();
  await expect(page.locator('tr:nth-child(3) > td:nth-child(5)')).toBeVisible();
  await expect(page.locator('tr:nth-child(3) > td:nth-child(6)')).toBeVisible();
  await expect(page.locator('tr:nth-child(3) > td:nth-child(7)')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'JOHN DEERE HEALTH CARE /' })).toBeVisible();
  await expect(page.locator('tr:nth-child(4) > td:nth-child(2)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(4) > td:nth-child(3)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(4) > td:nth-child(4)')).toBeVisible();
  await expect(page.locator('tr:nth-child(4) > td:nth-child(5)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(4) > td:nth-child(6)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(4) > td:nth-child(7)')).toBeVisible();
  await expect(page.getByRole('row', { name: 'JOHN DEERE HEALTH CARE /' }).getByRole('link')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'INTERFACE EAP (IEAP)' })).toBeVisible();
  await expect(page.locator('tr:nth-child(5) > td:nth-child(2)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(5) > td:nth-child(3)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(5) > td:nth-child(4)')).toBeVisible();
  await expect(page.locator('tr:nth-child(5) > td:nth-child(5)')).toBeVisible();
  await expect(page.locator('tr:nth-child(5) > td:nth-child(5)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(5) > td:nth-child(6)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(5) > td:nth-child(7)')).toBeVisible();
  await expect(page.getByRole('row', { name: 'INTERFACE EAP (IEAP) N/A N/A' }).getByRole('link')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'PUERTO RICO SSS MEDICARE' })).toBeVisible();
  await expect(page.locator('tr:nth-child(6) > td:nth-child(2)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(6) > td:nth-child(3)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(6) > td:nth-child(4) > checkbox > .checkbox')).toBeVisible();
  await expect(page.locator('tr:nth-child(6) > td:nth-child(5)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(6) > td:nth-child(6)')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('N/A');
  await expect(page.locator('tr:nth-child(6) > td:nth-child(7) > .add-group-btn')).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'Enter Payer Name or Id' }).nth(5)).toBeVisible();
  await page.getByRole('textbox').click();
  await expect(page.getByRole('textbox')).toBeEmpty();
  await page.getByRole('option', { name: '00046 - HILL PHYSICIANS' }).click();
  await expect(page.getByRole('button', { name: ' Add Payer' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Back' })).toBeVisible();
  await page.getByRole('button', { name: ' Add Payer' }).click();
  await expect(page.getByRole('cell', { name: 'HILL PHYSICIANS MEDICAL GROUP' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'TEST PAYER BY HAMZA' })).toBeVisible();
  await expect(page.locator('tr:nth-child(9) > td:nth-child(7) > .add-group-btn')).toBeVisible();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .add-group-btn').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('heading', { name: 'Add Group Enrollments' }).click();
  await expect(page.getByText('Group Name')).toBeVisible();
  await expect(page.getByRole('dialog').getByText('Group ID')).toBeVisible();
  await expect(page.getByRole('dialog').getByText('NPI')).toBeVisible();
  await expect(page.getByText(NPI)).toBeVisible();
  await expect(page.getByText(TAXID)).toBeVisible();
  await expect(page.getByText('Group Enrollment Records Added!')).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Records Failed to Add:' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Payer' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Type' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Close' })).toBeVisible();
  await page.getByRole('button', { name: 'Close' }).click();
  await expect(page.getByRole('cell', { name: groupId }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: groupName }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: NPI }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: TAXID }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'SELECTCARE' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'CLAIMSTATUS' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'RELAY' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'ELIGIBILITY' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'PROFESSIONAL' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'ERA' }).nth(4)).toBeVisible();
  await expect(page.getByRole('cell', { name: '73145' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '95092' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '6831' }).first()).toBeVisible();
 // await expect(page.getByRole('cell', { name: '00270' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: '95378' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '31441' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '60280' })).toBeVisible();

});